spring:
  datasource:
    url: jdbc:postgresql://postgres-server-mrts.postgres.database.azure.com:5432/pmrts?user=Gadmin&password=Admin@212&sslmode=require
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        use_sql_comments: true
server:
  servlet:
    context-path: /api/v1
  port: 8090
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: INFO
    app:
      MRTS: INFO
    org:
      springframework: INFO
  file:
    path: MRTSLogs
