package MRTS.DTO;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.util.Date;
import java.util.UUID;
@Data
public class ReportDto {
    private UUID reportId;
    @NotBlank(message = "Test Name is required")
    private String testName;
    @NotBlank(message = "Test Description is required")
    private String testDescription;
    @NotBlank(message = "Sample Type is required")
    private String sampleType;
    @NotBlank(message = "Test Result is required")
    private String testResult;
    @NotBlank(message = "Test Unit is required")
    private String testUnit;
    @NotBlank(message = "Normal Range is required")
    private String normalRange;
    @NotBlank(message = "Test Status is required")
    private String testStatus;
    @NotBlank(message = "Comments is required")
    private String comments;
    @NotNull(message = "Test Date is required")
    private Date testDate;
    @NotNull(message = "Report Generated Date is required")
    private Date reportGeneratedDate;
    @NotBlank(message = "Report Generated By is required")
    private String reportGeneratedBy;
    private UUID labTechnicianId;
    private UUID patientId;
    private UUID doctorId;
}
